node d:\scr\jd_blueCoin.js
node d:\scr\jd_shop.js
node d:\scr\fruit1.js
node d:\scr\jd_bean_home.js
node d:\scr\jd_car.js
node D:\scr\jd_car_exchange.js
node d:\scr\jd_cash.js
node D:\scr\jd_club_lottery.js
node d:\scr\jd_crazy_joy.js
node D:\scr\jd_dreamFactory.js
node D:\scr\jd_jdfactory.js
node d:\scr\jd_joy.js
node D:\scr\jd_daily_egg.js
node D:\scr\jd_family.js
node d:\scr\jd_jdzz.js
node d:\scr\jd_super_box.js
node d:\scr\jd_superMarket.js
node d:\scr\jd_syj.js
node d:\scr\jd_sgmh.js
node d:\scr\jd_kd.js
node d:\scr\jd_moneyTree.js
node d:\scr\jd_xgyl.js
node d:\scr\jx_sign.js
shutdown -s